

/* drop table if exist*/

DROP TABLE IF EXISTS JARDINS; 
DROP TABLE IF EXISTS JORNEMENT; 
DROP TABLE IF EXISTS JVERGER;
DROP TABLE IF EXISTS JPOTAGER;
DROP TABLE IF EXISTS PARCELLES;
DROP TABLE IF EXISTS RANG;
DROP TABLE IF EXISTS PLANTE; 
DROP TABLE IF EXISTS VARIETES;
DROP TABLE IF EXISTS SEMENCIER;
DROP TABLE IF EXISTS MENACES;
DROP TABLE IF EXISTS TYPESPRODUCTION; 
DROP TABLE IF EXISTS TYPESOL;
DROP TABLE IF EXISTS OCCUPER; 
DROP TABLE IF EXISTS BENEFICES;
DROP TABLE IF EXISTS INCONVENIENTS;
DROP TABLE IF EXISTS SUBIR;
DROP TABLE IF EXISTS COUVRIR;
DROP TABLE IF EXISTS ADAPTER;
DROP TABLE IF EXISTS PRODUIRE;
DROP TABLE IF EXISTS SAVOIR;

/* Creating tables */

CREATE TABLE JARDINS(
   idJ INTEGER NOT NULL AUTO_INCREMENT,
   nomJ VARCHAR(300),
   SurfaceJ INTEGER,
   idPa INTEGER REFERENCES PARCELLES (idPa),
   PRIMARY KEY (idJ)
  
);

CREATE TABLE JVERGER(
   idJV VARCHAR(300),
   HauteurMax VARCHAR(300),
   idJ VARCHAR(300) REFERENCES JARDINS(idJ),
   PRIMARY KEY(idJV, idJ)
);

CREATE TABLE JORNEMENT(
   idJO VARCHAR(300),
   idJ VARCHAR(300) REFERENCES JARDINS(idJ),
   PRIMARY KEY(idJO, idJ)
);

CREATE TABLE JPOTAGER(
   idJP VARCHAR(300),
   idJ VARCHAR(300) REFERENCES JARDINS(idJ),
   PRIMARY KEY(idJP, idJ)
);

CREATE TABLE PARCELLES(
   idPa VARCHAR(300) ,
   longitudePa FLOAT,
   latitudePa FLOAT,
   longueurPa FLOAT,
   largeurPa FLOAT,
   PRIMARY KEY(idPa)
);

CREATE TABLE RANG(
   idPa VARCHAR(300) REFERENCES PARCELLES(idPa),
   idRa VARCHAR(300),
   latitudeRa FLOAT,
   longitudeRa FLOAT,
   PRIMARY KEY(idPa, idRa)
);

CREATE TABLE PLANTE(
   nomPl VARCHAR(300),
   nomlatinPL VARCHAR(300),
   catégoriePL VARCHAR(300),
   typePL VARCHAR(300),
   soustypePL VARCHAR(300),
   PRIMARY KEY(nomPl)
);

CREATE TABLE VARIETES(
   idV INTEGER NOT NULL AUTO_INCREMENT,
   nomV VARCHAR(300),
   anneeV VARCHAR(300),
   precocite VARCHAR(300),
   descriptionSemis VARCHAR(300),
   plantation VARCHAR(300),
   entretien VARCHAR(300),
   recolteV VARCHAR(300),
   nbjourlevee VARCHAR(200),
   commentaireV VARCHAR(300),
   debutMEP VARCHAR(300),
   finMEP VARCHAR(300),
   debutRecolte VARCHAR(300),
   finRecolte VARCHAR(300),
   PRIMARY KEY(idV),
   nomPl VARCHAR(300) REFERENCES PLANTE(nomPl)
);

CREATE TABLE SEMENCIER(
   idS INTEGER NOT NULL AUTO_INCREMENT,
   nomS VARCHAR(300),
   siteweb VARCHAR(300),
   PRIMARY KEY(idS)
);

CREATE TABLE MENACES(
   idM VARCHAR(300),
   descriptionM VARCHAR(300),
   listesolutionsM VARCHAR(300),
   PRIMARY KEY(idM)
);

CREATE TABLE TYPESPRODUCTION(
   idT VARCHAR(300),
   biologique VARCHAR(300),
   conventionnelle VARCHAR(300),
   PRIMARY KEY(idT)
);

CREATE TABLE TYPESOL(
   typeSol VARCHAR(300),
   PRIMARY KEY(typeSol)
);


CREATE TABLE OCCUPER(
   idPa INTEGER REFERENCES PARCELLES(idPa),
   idRa INTEGER REFERENCES RANG(idRa),
   idV VARCHAR (200) REFERENCES VARIETES(idV),
   DateDeb VARCHAR(200) REFERENCES PERIODES(DateDeb),
   DateFin VARCHAR(200) REFERENCES PERIODES(DateFin),
   typeMEP VARCHAR(200),
   commentaire VARCHAR(200),
   qualite VARCHAR(200),
   quantite VARCHAR(200),
   PRIMARY KEY(idPa, idRa, idV, DateDeb, DateFin)
);

CREATE TABLE BENEFICES(
   nomPl1 VARCHAR(300) REFERENCES PLANTE (nomPl1),
   nomPl2 VARCHAR(300) REFERENCES PLANTE(nomPl2),
   PRIMARY KEY(nomPl1, nomPl2)
);

CREATE TABLE INCONVENIENTS(
   nomPl1 VARCHAR(300) REFERENCES PLANTE(nomPl1),
   nomPl2 VARCHAR(300) REFERENCES PLANTE(nomPl2),
   PRIMARY KEY(nomPl1, nomPl2)
);

CREATE TABLE SUBIR(
   nomPl VARCHAR(300) REFERENCES PLANTE(nomPl),
   idM VARCHAR(300) REFERENCES MENACES(idM),
   PRIMARY KEY(nomPl, idM)
);

CREATE TABLE COUVRIR(
   idPa INTEGER REFERENCES PARCELLES(idPa),
   idRa INTEGER REFERENCES RANG(idRa),
   nomPl VARCHAR(200) REFERENCES PLANTE(nomPl),
   DateDeb VARCHAR(200) REFERENCES PERIODES(DateDeb),
   DateFin VARCHAR(200) REFERENCES PERIODES(DateFin),
   PRIMARY KEY(idPa, idRa, nomPl, DateDeb, DateFin)
);

CREATE TABLE ADAPTER(
   idJ1 VARCHAR(300) REFERENCES JPOTAGER(idJ1),
   idV VARCHAR(300) REFERENCES VARIETES(idV),
   decision VARCHAR(300),
   PRIMARY KEY(idJ1, idV)
  
);

CREATE TABLE PRODUIRE(
   idV VARCHAR(300) REFERENCES VARIETES(idV),
   idS INTEGER REFERENCES SEMENCIER(idS),
   idT VARCHAR(300) REFERENCES TYPES(idT),
   PRIMARY KEY(idV, idS, idT)

);

CREATE TABLE SAVOIR(
   idJ VARCHAR(300) REFERENCES JARDINS(idJ),
   typeSol VARCHAR(300) REFERENCES TYPESOL(typeSol),
   PRIMARY KEY(idJ, typeSol)
);

/* Inserting instances */ 

INSERT INTO VARIETES (nomV, anneeV, precocite, commentaireV,nomPl)
SELECT codeVariété, annéeEnregistrement, labelPrécocité, commentaire,nomEspèce FROM dataset.DonneesFournies;

INSERT INTO PLANTE (nomPl, nomlatinPl, typePl, soustypePl)
SELECT T.nomEspèce, T.nomEspèceLatin, T.type, T.sousType FROM (
SELECT nomEspèce, nomEspèceLatin, type, sousType 
FROM dataset.DonneesFournies
GROUP BY nomEspèce) AS T;

